name: mlops-test
on:
  pull_request:
    types: [ opened, synchronize ]
    branches:
      - 'main'
jobs:
  train-model-ci:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    
      - name: Install dependencies
        run: |
          pip install -r requirements.txt